### ISSUE TITLE
Can't install using Carthage

### ISSUE THREAD

**Issue by davidpasztor** [AnderGoig/InstagramLogin#1]
When trying to build your framework using Carthage, I get the following error:

>Dependency "InstagramLogin" has no shared framework schemes

Full Terminal output:

> carthage update                                                                                                                                                                            
> *** Fetching InstagramLogin
> *** Checking out InstagramLogin at "v1.2.0"
> *** xcodebuild output can be found in /var/folders/rx/jxm8sgs10tb0d3b3ndvpgygw0000gn/T/carthage-xcodebuild.cNZPbK.log
> *** Skipped building InstagramLogin due to the error:
> Dependency "InstagramLogin" has no shared framework schemes
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/AnderGoig/InstagramLogin/issues/new

My Cartfile only has this single line:
`github "AnderGoig/InstagramLogin"`

**Comment by AnderGoig** [comment]
Thanks for notifying me! Should be fixed in v1.2.1
